---
title: "Demographics_for_gumballs"
author: "Arndis"
date: "17/4/2020"
output: html_document
---

```{r}

pacman::p_load(tidyverse,dplyr,haven,readr,readxl)


setwd("C:/Users/AU251961/Dropbox/Stuff we share/Work/PhD_Data")
Data=read.table('FO_interviewsALL.txt', sep="\t", header=TRUE)
Edu=read.table('Matching participants, updated years of education 29-06-15.txt', sep="\t", header=TRUE)
Meds <- read_excel("C:/Users/AU251961/Dropbox/Stuff we share/Work/PhD_Data/Medication CPZe 10-02-17 updated according to Leucht 2014, Gardner 2010 for gumballs.xls")

# This is the original SPSS interviewer dataset output with all variables. Some of these columns have been removed from the "FO_interviewsAll"
DataRaw <- read_sav("C:/Users/AU251961/Dropbox/fra dropbox/1. Schizophrenia/1.datasheets social/SPSS interviewer/SOCIAL_FO_2_1_opbygning af kombineret datasaet.sav")

#Living <- read_delim("C:/Users/AU251961/Dropbox/fra dropbox/1. Schizophrenia/1.datasheets social/Physical #and other charactaristics.csv", ";", escape_double = FALSE, trim_ws = TRUE)

Living <- read.csv("C:/Users/AU251961/Dropbox/fra dropbox/1. Schizophrenia/1.datasheets social/Physical and other charactaristics.csv", sep=";")

Tasit <- read.delim("C:/Users/AU251961/Dropbox/Stuff we share/Work/scripts/logfiles/TasitResults12-Nov-2014.txt")

IQ <- read.csv("C:/Users/AU251961/Dropbox/Stuff we share/Work/PhD_Data/Estimated IQ SOCIAL 10.10.14.csv", sep=";")

SWM <- read.csv("C:/Users/AU251961/Dropbox/Stuff we share/Work/PhD_Data/SWM.csv", sep=";")
IED <- read.csv("C:/Users/AU251961/Dropbox/Stuff we share/Work/PhD_Data/IED.csv", sep=";")


# Excluded participants and participants that did not perform the task/dropped out 
# First round of exclusion/drop outs: 10 patients, 2 controls
# Second round (111 (drugs), 117(minus comprehension), 118 (minus comprehension), 122 (no time),145 (alcohol, epilepsy?))
ExclParticipants=c(102,107,108,109,111,114,115,117,118,119,120,122,123,124,145,205,217)

# Create Group variable
Data$Group[Data$Subject_ID<200]='Schizophrenia'
Data$Group[Data$Subject_ID>200]='Control'

Edu$Group[Edu$ID<200]='Schizophrenia'
Edu$Group[Edu$ID>200]='Control'

Living$Group[Living$ID<200]='Schizophrenia'
Living$Group[Living$ID>200]='Control'

IQ$Group[IQ$ID<200]='Schizophrenia'
IQ$Group[IQ$ID>200]='Control'

SWM$Group[SWM$Subject_ID<200]='Schizophrenia'
SWM$Group[SWM$Subject_ID>200]='Control'

IED$Group[IED$Subject_ID<200]='Schizophrenia'
IED$Group[IED$Subject_ID>200]='Control'


Data <- Data[!(Data$Subject_ID %in% ExclParticipants), ]
Edu <- Edu[!(Edu$ID %in% ExclParticipants), ]
Meds <- Meds[!(Meds$Subject_ID %in% ExclParticipants), ]
DataRaw <- DataRaw[!(DataRaw$Subject_ID %in% ExclParticipants), ]
Living <- Living[!(Living$ID %in% ExclParticipants), ]
Tasit <- Tasit[!(Tasit$Subject %in% ExclParticipants), ]
IQ <- IQ[!(IQ$ID %in% ExclParticipants), ]
SWM <- SWM[!(SWM$Subject_ID %in% ExclParticipants), ]
IED <- IED[!(IED$Subject_ID %in% ExclParticipants), ]
```


```{r}
# Data til Tabel 1

tapply(Data$Age, Data$Group, mean)
tapply(Data$Age, Data$Group, sd)

tapply(Edu$Gender, Edu$Group, summary)

# replace , with . in years_edu
Edu$years_edu <- gsub(",",".",Edu$years_edu)
Edu$years_edu <- as.numeric(Edu$years_edu)

tapply(Edu$years_edu, Edu$Group, summary)
tapply(Edu$years_edu, Edu$Group, sd)

tapply(Data$PSP_total_score, Data$Group, summary)
tapply(Data$PSP_total_score, Data$Group, sd)

tapply(Edu$edu_level_started, Edu$Group, summary) 
tapply(Edu$edu_level_started, Edu$Group, sd) 

Edu$social_no=as.factor(Edu$social_no)
tapply(Edu$social_no, Edu$Group, summary)

tapply(Edu$Handedness, Edu$Group, summary)

Data$Global_Rating_Avolition_Apathy_rating[Data$Global_Rating_Avolition_Apathy_rating==6]=NA #This is the only symptom variable that has 6 instead of NA


# Calculate SANS & SAPS, CPZ
Data$SAPS=Data$Global_hallucination_rating+Data$Global_Rating_Severity_Delusions_rating+Data$Global_Rating_Severity_Bizarre_Behavior_rating+Data$Global_Rating_Formal_Thought_Disorder_rating

Data$SANS=Data$Global_Rating_Affective_Flattening_rating+Data$Global_Rating_Alogia_rating+Data$Global_Rating_Avolition_Apathy_rating+Data$Global_Rating_Anhedonia_Asociality_rating+Data$Global_Rating_of_Attention_rating

mean(Data$SAPS, na.rm=T) #4.2
sd(Data$SAPS, na.rm=T) #4.128808

mean(Data$SANS, na.rm=T) #7.657143
sd(Data$SANS, na.rm=T) #4.633274

mean(Data$Global_hallucination_rating, na.rm=T) # 1.314286
sd(Data$Global_hallucination_rating, na.rm=T) # 1.936817

mean(Data$Global_Rating_Severity_Delusions_rating, na.rm=T) # 1.885714
sd(Data$Global_Rating_Severity_Delusions_rating, na.rm=T) # 2.025883

mean(Data$Global_Rating_Severity_Bizarre_Behavior_rating, na.rm=T) # 0.4857143
sd(Data$Global_Rating_Severity_Bizarre_Behavior_rating, na.rm=T) # 0.9194445

mean(Data$Global_Rating_Formal_Thought_Disorder_rating, na.rm=T) # 0.5142857
sd(Data$Global_Rating_Formal_Thought_Disorder_rating, na.rm=T) # 0.9813385

mean(Data$Global_Rating_Affective_Flattening_rating, na.rm=T) # 1.342857
sd(Data$Global_Rating_Affective_Flattening_rating, na.rm=T) # 1.109925

mean(Data$Global_Rating_Alogia_rating, na.rm=T) # 0.8571429
sd(Data$Global_Rating_Alogia_rating, na.rm=T) # 1.309307

mean(Data$Global_Rating_Avolition_Apathy_rating, na.rm=T) # 2.342857
sd(Data$Global_Rating_Avolition_Apathy_rating, na.rm=T) # 1.211291

mean(Data$Global_Rating_Anhedonia_Asociality_rating, na.rm=T) # 1.971429
sd(Data$Global_Rating_Anhedonia_Asociality_rating, na.rm=T) # 1.484938

mean(Data$Global_Rating_of_Attention_rating, na.rm=T) # 1.142857
sd(Data$Global_Rating_of_Attention_rating, na.rm=T) # 1.396274

mean(Meds$CPZ_total, na.rm=T) # 702.8314
sd(Meds$CPZ_total, na.rm=T) # 577.3198

# Schizo-affective patients: 4 i alt (bedste estimat pba. de givne oplysninger under diagnostisk interview samt cosmic diagnose ud fra indlæggelser siden 2011)
Lit_antiep <- Meds[c("Subject_ID", "lithium", "antiepileptic", "antidepressant")]
# 112 kunne være skizoaffektiv (bliver primært manisk, ikke depressiv), får litium, men diagnose i cosmic er paranoid skizofreni, så den holder vi os til
# 148 kunne være skizoaffektiv (præget af depressive symptomer, har tidligere fået asparger diagnose), får anitepileptisk medicin for bipolar, men diagnose i cosmic siger paranoid skizofreni, så den holder vi os til


# 130 står til at være skizoaffektiv i cosmic, så den holder vi os til
# 134 har opfyldt skizoaffektiv (baseret på interview, nu præget af depressive symptomer), får antidepressiva
# 141 har opfyldt skizoaffektiv (baseret på interview). Har tidligere fået diagnoserne bipolær og skizotypi, får antiepileptisk medicin
# 142 opfyldte kun diagnosen for skizoaffektiv pga. varighed, cyklisk forløb. Får ikke medicin


#Living situation, work/pension, illness duration (OBS! kun systematisk udfyldt ift. til de 35 patienter, der er analyseret i gumballs)
# Jeg har lavet tre nye variable (hvordan de bor, hvordan de får penge og hvor længe de har været syge (bedste estimat ud fra de givne oplysninger, se kommentarfelt for baggrundsinfo til denne variabel)) i den fil der hedder "Physical and other charactaristics" i 1.datasheets social mappen (her omdøbt til Living)

Living$Living_sit=as.factor(Living$Living_sit)
tapply(Living$Living_sit, Living$Group, summary)

#$Control
# independent  institution with parents 
#          37            0            3 
#
#$Schizophrenia
# independent  institution with parents 
#          13            7           15 

LivingSit <- Living[c("ID", "Group", "Living_sit", "Financial_support")]

tapply(LivingSit$Financial_support, Living$Group, summary)

mean(Living$Illness_duration, na.rm=T) # 14.68571
sd(Living$Illness_duration, na.rm=T) # 9.812272

DataRawSupport <- DataRaw[c("Subject_ID", "Current_work_living_support", "Diagnosis", "Age_of_onset","Diagnosis_duration", "Medication_detail", "Living_support10","Years_of_pension", "Working_hours")]

# TASIT, IQ, SWM, IED
# TASIT
tapply(Tasit$RightAnswers, Tasit$Schizophrenia, summary)

# $`0`
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   32.00   46.75   49.50   49.70   53.25   59.00 
# 
# $`1`
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   24.00   41.00   46.00   44.46   49.00   56.00 

tapply(Tasit$RightAnswers, Tasit$Schizophrenia, sd)
#       0        1 
# 5.426431 7.333817 

#IQ
tapply(IQ$est..Full..IQ, IQ$Group, summary)
# $Control
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    70.0    96.0    99.0   102.5   110.5   132.0 
# 
# $Schizophrenia
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   73.00   82.00   88.00   93.31  106.50  122.00 

tapply(IQ$est..Full..IQ, IQ$Group, sd)
#     Control Schizophrenia 
#     13.81554      14.39316 

# SWM
tapply(SWM$SWM_Total_errors, SWM$Group, summary)
# $Control
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    0.00    0.00    6.00    7.60   10.75   35.00 
# 
# $Schizophrenia
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    0.00    9.00   15.00   16.06   23.50   40.00 

tapply(SWM$SWM_Total_errors, SWM$Group, sd)

#     Control Schizophrenia 
#     8.998005     10.490732 

# IED
tapply(IED$IED_Total_errors_adj, IED$Group, summary)

# $Control
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     5.0     9.0    11.0    18.6    20.5    59.0 
# 
# $Schizophrenia
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    9.00   14.50   27.00   42.11   56.00  179.00 

tapply(IED$IED_Total_errors_adj, IED$Group, sd)

#     Control Schizophrenia 
#     16.07642      39.29434 
```


```{r}


```

